### PR TITLE
Finished commands, weird math for shooter; needs tuning

### PR DESCRIPTION
**Pull request by aaditsangvikar**
A lot of changes- this should be a pretty finished command base, besides for all the tuning that needs to happen.

### CODE REVIEW

**Comment by aaditsangvikar** [comment]
So there's also going to be a belt ratio thing for the shooter, so the actual wheel speeds compared to the motor rpm will be different, which is something we have to take into account.

**Review by TotalTaxAmount — COMMENTED** [review]
Idk if this is what is supposed to be changed but all that this pr does is move the constants file into the constants directory at create a ShooterUtils class

**Comment by aaditsangvikar** [comment]
Ah I didn't push the full thing by accident, it should be actually committed now.

**Review by TotalTaxAmount — APPROVED** [review]
Looks good, MathUtils.inRange and Math.clamp do the same thing I believe. No reason to have a MathUtils.inRange. ShooterUtils.findRoot could take some compute time as we will be calling it over and over but it should be fine

**Comment by aaditsangvikar** [comment]
Math.clamp doesn't exist in Java 17, which is what WPILib wants(for some reason).

Also, there are faster root finding methods that converge less predictably we can look into if we run into issues with bisection.

**Comment by TotalTaxAmount** [comment]
Java 21  is backwards compatible to like Java 8 or smth. Maybe it wants 17 but we can use 21, don't see any reason why not.

I don't completely understand the math for you find root stuff just glancing over it so if you think it's fine then it probably is as long as it doesn't take more than 20ms to do one find I think it's ok

**Comment by aaditsangvikar** [comment]
Hmm okay alright, I'll switch out the math utils stuff for the Math.clamp

**Review by ddjoshua01 — APPROVED** [review]

**Pull request merged**
